apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-microservice-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-microservice-app
  template:
    metadata:
      labels:
        app: flask-microservice-app
    spec:
      containers:
      - name: flask-microservice-app
        image: horlar/flask-microservice-app:0.2
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 5000
